### ISSUE TITLE
Unhandled Rejection (TypeError): err.response is undefined on code PIN

### ISSUE THREAD

**Issue by gorinje** [computationalprivacy/unveil-deployment#1]
Hi,

I'm trying to deploy your demo on our own server using the default parameters. However, the (our server IP)/control ask for a stric PIN code of 6 numbers where the [default configuration file](https://github.com/computationalprivacy/unveil-deployment/blob/master/configs/change_me.production.py) is set to 8 numbers. Even when reducing the default password to 6, the authentification interface constantly returns this error :
```

Unhandled Rejection (TypeError): err.response is undefined
Controller/this.onKeyPress/<
src/components/Controller.js:163

  160 |         }
  161 |     ).catch(
  162 |         err => {
> 163 |             this.setState({ errorMsg: err.response.data.error });
      | ^  164 |         }
  165 |     );
  166 | }

This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

**Comment by shubhamjain0594** [comment]
Hi Gorinje, thanks for trying out and letting us know.

a) We have fixed the length of pin to max 6 for usability on the frontend side. We will add it to the README, thanks for letting us know.
b) For the error, can you check and let us know if the server is receiving the request? Can you also check the URLs in config file for frontend are set properly? I remember seeing this error when server doesn't receive the request. You can do this by looking at the logs of django (under logs folder) or also the console on the browser if it gives any error.

**Comment by gorinje** [comment]
Many thanks for your answer.

From http://(ourIP):3000/control, the POST request for the verification PIN is indeed sent to this location :
http://localhost:8000/access/verify/

instead of our remote server :
http://(our IP):8000/access/verify/

although runtimeConfig.js is correctly set to the server IP. 

In which file this information should be set in order to send this request to the correct location?

Can you also tell us which file allows to change this default PIN?

**Comment by shubhamjain0594** [comment]
Hello,

1. The `runtimeConfig.js` should be in the path `configs/runtimeConfig.js`. Can you check in `unveil-deployment.yml` that right file is being loaded?
2. To change the PIN you have to set it in `configs/production.py` at line: 46. And you can set maximum of length 6. To set a larger PIN you might want to change it in [this file](https://github.com/computationalprivacy/unveil-frontend/blob/cc0bbd32bc635c716f45fbeb03aa33826a946680/src/components/Controller.js#L208)

**Comment by gorinje** [comment]
The deployement file has been updated accordingly and it now works. Many thanks!
